### ISSUE TITLE
Allow chats to be saved automatically

### ISSUE THREAD

**Issue by JaredDanielJones** [marcolivierbouch/OpenAssistantGPT#256]
Having chats save automatically instead of only when the user submits an inquiry would allow me to improve the chatbot prompt more effectively.

Love this project. Hope to support development soon

**Comment by marcolivierbouch** [comment]
Hello @JaredDanielJones, there is currenctly no builtin solution for this since you can enable threads in OpenAI. You can follow our documentation if you are interested. On the long term it would definetly be a feature that we want to integrate.

[https://www.openassistantgpt.io/guides/how-to-see-all-your-chatbot-threads](https://www.openassistantgpt.io/guides/how-to-see-all-your-chatbot-threads)

**Comment by JaredDanielJones** [comment]
Perfect I didn't realize I could do that. Thanks
